version: '3.7'

services:
  api:
    build: .
    command: bash -c "python app/main.py"
    container_name: api
    volumes:
      - ./database/:/usr/src/app/database
    ports:
      - 7777:7777
    restart: always